---
title: 'Aula 01: Introdução do curso'
author: "Bruno Pinheiro"
date: '2018-08-22'
css: style.css
---

  <link rel="stylesheet" href="style.css" type="text/css" />


<div id="r-e-rstudio" class="section level2">
<h2>R e RStudio</h2>
<p>O <code>R</code> é um ambiente e também uma linguagem para a computação estatística e a produção de gráficos. Basicamente é um programa de linha de comando<sup><a href="#fig:R">1</a></sup>, que permite acessar, manipular e visualizar dados, criando e guardando rotinas de análise que podem ser compartilhadas e replicadas tanto na forma de <em>scripts</em> como na forma de pacotes.</p>
<p>O programa surgiu em meados dos anos 1990 como uma alternativa para computação estatística (gratuita e de código aberto) feita para profissionais cuja origem não era a das ciências da computação. A linguagem <code>R</code> é uma implementação da linguagem S e seu desenvolvimento é gerido pela <em>R Foundation</em> (<a href =
"https://www.r-project.org/about.html", target = "_blank">clique aqui para saber mais</a>).</p>
<div id="interface-do-r" class="section level3">
<h3>Interface do R</h3>
<div class="figure" style="text-align: center"><span id="fig:R"></span>
<img src="img/interface-r.png" alt="Interface do R" width="80%" height="80%" />
<p class="caption">
Figure 1: Interface do R
</p>
</div>
<p>O <code>R</code> está disponível para usuários de Linux, Windows e OS X (Mac). Nos últimos 10 anos, principalmente, vem tornando-se uma ferramenta bastante popular. Entre as razões principais desta popularidade, podemos citar:</p>
<ul>
<li><p>É fácil estender capacidades do programa ou sistematizar modelos de análise com novas funções e pacotes;</p></li>
<li><p>Viabiliza todo o ciclo da ciência de dados, da coleta dos dados à comunicação dos resultados;</p></li>
<li><p>É código aberto, gratuito</p></li>
<li><p>Tem uma grande comunidade que dá suporte por listas de e-mail, com documentações e tutoriais e que é bastante ativa no <a href = "https://stackoverflow.com/", target = "blank_">Stack Overflow</a>;</p></li>
<li><p>Tem um ambiente de desenvolvimento (<em>IDE</em>, <em>Integrated Development Environment</em>, da sigla em inglês) sólido, o RStudio, que vem evoluindo rapidamente, ganhando robustez e maiores possibilidades de uso;</p></li>
<li><p>É uma das linguagens estatísticas de mais rápido crescimento em termos de usuários gerais e também no mundo corporativo.</p></li>
</ul>
<p>Um dado impressionante, por exemplo, e que expressa o crescimento do uso do <code>R</code>, é a evolução da quantidade de pacotes disponíveis no <a href =
"https://cran.r-project.org/", target = "blank_">CRAN (Comprehensive R Archive Network)</a>, conforme figura abaixo<sup><a href="#fig:cran">2</a></sup>. Os pacotes são como compilados de funções e dados que podem ser instalados no <code>R</code> e o CRAN é um repositório de pacotes, com o qual os usuários podem contribuir e disponibilizar os pacotes criados.</p>
<div class="figure" style="text-align: center"><span id="fig:cran"></span>
<img src="/aula01/index_files/figure-html/cran-1.png" alt="Número de pacotes publicados no CRAN" width="80%" height="80%" />
<p class="caption">
Figure 2: Número de pacotes publicados no CRAN
</p>
</div>
<p>Além disso o <code>R</code> tem um poderoso IDE, chamado de <a href = 
"https://www.rstudio.com/", target = "blank_">RStudio</a>, que oferece uma interface muito amigável para uso do programa<sup><a href="#fig:RStudio">3</a></sup>. Mantendo o foco na linha de comando, ele extende as funcionalidades do <code>R</code> otimizando a criação e gestão de projetos, facilitando a edição de <em>scripts</em>, além de agregar na mesma interface áreas que dão acesso aos códigos, aos objetos, aos arquivos, às visualizações e outras ferramentas.</p>
</div>
<div id="interface-do-rstudio" class="section level3">
<h3>Interface do RStudio</h3>
<div class="figure" style="text-align: center"><span id="fig:RStudio"></span>
<img src="img/interface-rstudio.png" alt="Interface do RStudio" width="80%" height="80%" />
<p class="caption">
Figure 3: Interface do RStudio
</p>
</div>
<p>A imagem acima mostra a interface do RStudio. É importante conhecermos ao menos o básico do seu ambiente de trabalho, pois será com ele que trabalharemos no curso. As áreas que mais usaremos serão as seguintes:</p>
<ul>
<li><p><strong>Editor/Scripts</strong>: é o quadrante superior à esquerda, onde escrevemos os códigos para guardar;</p></li>
<li><p><strong>Console</strong>: é o quadrante inferior à esquerda, onde o código do <code>R</code> é rodado e onde são geradas as saídas. É o mesmo que o <code>R</code> básico que vimos acima no terminal<sup><a href="#fig:R">1</a></sup>;</p></li>
<li><p><strong>Environment</strong>: é o painel superior à direita. Nele acessamos os objetos criados durante a sessão de trabalho. Além disso já outras abas. Uma muito útil é a <strong>History</strong>, onde ficam registradas todas as linhas de código que foram rodadas.</p></li>
<li><p><strong>Files</strong>: é o painel inferior à direita e funciona como uma ferramenta de navegação aos arquivos, dando acesso direto ao diretório de trabalho. Este painel é objeto de atenção constante, pois as demais abas são ativadas quando plotamos algum gráfico (<strong>Plots</strong>), quando acessamos a ajuda (<strong>Help</strong>) ou quando criamos algum documento ou visualização dinâmica (<strong>Viewer</strong>).</p></li>
</ul>
</div>
<div id="atalhos-do-rstudio" class="section level3">
<h3>Atalhos do RStudio</h3>
<p>Além disso, quando estamos digitando nossos códigos, é muito útil conhecer alguns atalhos do teclado, que facilitam a vida. Abaixo estão alguns dos principais:</p>
<ul>
<li><p><code>CTRL+ENTER</code>: roda a linha selecionada no script. Os atalhos mais utilizado.</p></li>
<li><p><code>ALT+-</code>: (&lt;-) sinal de atribuição. Você usará o tempo todo.</p></li>
<li><p><code>CTRL+SHIFT+M</code>: (%&gt;%) operador pipe. Guarde esse atalho, você usará bastante.</p></li>
<li><p><code>CTRL+1</code>: altera cursor para o script.</p></li>
<li><p><code>CTRL+2</code>: altera cursor para o console.</p></li>
<li><p><code>CTRL+ALT+I</code>: cria um chunk no R Markdown.</p></li>
<li><p><code>ALT+SHIFT+K</code>: janela com todos os atalhos disponíveis.</p></li>
</ul>
<p>Não se preocupe se neste momento você ainda não consegue entender exatamente o que eles significam. No decorrer do curso entederemos. Guarde apenas que existem atalhos muito úteis, que há esta sessão apresentando alguns principais e que, se quiser conhecer mais atalhos, basta digitar o último indicado acima: <code>ALT+SHIFT+K</code>.</p>
<p>Caso disponha de um computador pessoal, é fortemente indicado que você instale o <code>R</code> e o RStudio nele. Desta forma você poderá estudar o material em sua casa, experimentar a aplicação do RStudio para realizar tarefas que você faria com outros programas e, inclusive, pode utilizar este material para estudo do <code>R</code> mesmo sem participar do curso presencial 😉.</p>
<hr />
</div>
</div>
<div id="o-basico-do-r" class="section level2">
<h2>O básico do R</h2>
<p>Durante o curso utilizaremos a linguagem de análise de dados oriunda do conjunto de pacotes conhecido como <code>tidyverse</code> (<a href = "https://www.tidyverse.org/, target = "blank_">conheça</a>), criado para facilitar o uso do <code>R</code> para a ciência de dados. Trata-se de uma abordagem mais estruturada que a sintaxe da chamada base do <code>R</code>, e mais fácil de aprender.</p>
<p>Os pacotes do <code>tidyverse</code> que usaremos são os seguintes:</p>
<ul>
<li><p><code>dplyr</code> para manipular os dados</p></li>
<li><p><code>tidyr</code> para “arrumar” os dados</p></li>
<li><p><code>ggplot2</code> para visualizar os dados</p></li>
</ul>
<p>Nesta aula começaremos a usar alguns dos pacotes do <code>tidyverse</code>. Porém o foco será experimentar e conhecer aspectos como a sintaxe básica do <code>R</code>, operadores, formas de usar as funções e de obter ajudar quando há alguma dúvida (acredite, mesmo os usuários mais avançados utilizam muito este recurso). Na próxima aula é que daremos um mergulho mais profundo nas funções de manipulação e visualização dos pacotes do <code>tidyverse</code>.</p>
<div id="linha-de-comando-e-operacoes-basicas" class="section level3">
<h3>Linha de comando e operações básicas</h3>
<p>A linha de comando é onde tudo acontece no <code>R</code>. Para usuários iniciantes a tela do console pode parecer um tanto abastrata, às vezes meio assustadora. Mas pode ter certeza que com o tempo vira costume.</p>
<p>Para começar, não tem outro jeito. É preciso digitar e rodar comandos na linha de comando para ver o que acontece. Usar o <code>R</code> como uma calculadora é uma boa forma de experimentar. Como é um pacote feito para análises estatísticas, todo tipo de operações matemáticas podem ser realizadas.</p>
<p>Vamos começar realizando algumas operações básicas de soma, subtração, multiplicação, divisão e potência. Digite os comandos a seguir no console do <code>R</code> e veja o que acontece.</p>
<pre class="r"><code>1 + 1 # adição</code></pre>
<pre><code>## [1] 2</code></pre>
<pre class="r"><code>4 - 2 # subtração</code></pre>
<pre><code>## [1] 2</code></pre>
<pre class="r"><code>2 * 3 # multiplicação</code></pre>
<pre><code>## [1] 6</code></pre>
<pre class="r"><code>5 / 2 # divisão</code></pre>
<pre><code>## [1] 2.5</code></pre>
<pre class="r"><code>4 ^ 2 # potência</code></pre>
<pre><code>## [1] 16</code></pre>
<div class="admonition warning">
<p class="admonition-title">
<em>Experimente</em>
</p>
<p>
Pare um tempo para experimentar outras operações e, inclusive, tente incluir mais de uma operação no mesmo comando, como <code>17 * 3 / 65</code>.
</p>
</div>
<p>Agora que já experimentou, vamos tentar algo um pouco diferente. Ao invés de realizarmos uma operação com valores únicos, vamos realizar uma operação matemática com dois vetores de dados.</p>
<p>Primeiro vamos criar os vetores:</p>
<pre class="r"><code># criar vetores
x &lt;- c(1, 2, 3, 4)
y &lt;- c(2, 3, 5, 6)</code></pre>
<p>A função <code>c()</code> combina valores em um único vetor de dados. O que fizemos acima, então, foi criar dois vetores com 4 valores cada. Podemos acessar estes objetos digitando o nome deles na linha de comando.</p>
<pre class="r"><code>x</code></pre>
<pre><code>## [1] 1 2 3 4</code></pre>
<pre class="r"><code>y</code></pre>
<pre><code>## [1] 2 3 5 6</code></pre>
<p>Agora sim, vamos realizar uma operação de soma para ver o que ocorre:</p>
<pre class="r"><code>x + y</code></pre>
<pre><code>## [1]  3  5  8 10</code></pre>
<p>O resultado é a soma dos valores correspondentes em cada vetor. Ou seja, o primeiro valor de <code>x</code> foi somado com o primeiro valor de <code>y</code>, o segundo valor de <code>x</code> somado com o segundo valor de <code>y</code>, e assim por diante.</p>
<div class="admonition warning">
<p class="admonition-title">
<em>Experimente</em>
</p>
<p>
Mais uma vez, detenha-se aqui um instante e experimente realizar outras operações com os vetores <code>x</code> e <code>y</code> na sua linha de comando.
</p>
</div>
<p>Mais adiante começaremos a trabalhar com conjuntos de dados com milhares de observações. Entender esta lógica ajudará a realizar operações com as variáveis desses dados.</p>
<p>Antes de avançar, neste tópico introduzimos outro operador muito importante: o sinal de atribulição <code>&lt;-</code>. Ele é usado para guardar dados em um objeto. O que ele faz é estocar todos os valores passados à direita no objeto indicado à esquerda. Assim, quando rodamos o comando <code>x &lt;- c(1, 2, 3, 4)</code> o que fizemos foi dizer: “Ei, <code>R</code>! Guarde os valores 1, 2, 3 e 4 no objeto <code>x</code>”.</p>
</div>
<div id="instalar-pacotes" class="section level3">
<h3>Instalar pacotes</h3>
<p>Para continuar, a primeira coisa que precisamos fazer é instalar os pacotes. A instalação de pacotes pode ser feita de três formas: direto do CRAN, do GitHub, ou por arquivos de compilação. Neste curso basicamente utilizaremos a primeira função, mas detalharemos também como instalar do GitHub:</p>
<div id="instalacao-do-cran" class="section level4">
<h4>Instalação do CRAN</h4>
<p>Dentro do <code>R</code> basta digitar e rodar no console a função <code>install.packages(&quot;pacote&quot;)</code> que automaticamente o pacote será buscado no CRAN, baixado e instalado. Vamos experimentar esta função para instalar o <code>tidyverse</code>.</p>
<pre class="r"><code>## Instalar pacote
# install.packages(&quot;tidyverse&quot;)</code></pre>
<p>Você verá que uma série de pacotes serão instalados. Isto é porque além dos pacotes próprios do <code>tidyverse</code> todas as dependências também são instaladas automaticamente.</p>
</div>
<div id="instalacao-do-github" class="section level4">
<h4>Instalação do GitHub</h4>
<p>O CRAN funciona como um repositório com as últimas versões oficiais dos pacotes. Já o GitHub funciona como um repositório no qual os desenvolvedores hospedam o código dos pacotes e colaboram para aperfeiçoá-lo. Isto significa que as versões dos pacotes ali hospedadas são mais recentes que as disponíveis no CRAN.</p>
<p>Além disso nem todos os pacotes já criados estão disponíveis no CRAN, de modo que às vezes a única opção é utilizar a instalação pelo GitHub. O pacote <code>devtools</code> dispõe da função <code>install_github()</code> que faz o trabalho de baixar e instalar diretamente do GitHub.</p>
<p>Se fossemos instalar a versão do <code>tidyverse</code> presente no GitHub, por exemplo, faríamos da seguinte forma:</p>
<pre class="r"><code>## Instalar o pacote devtools
# install.packages(&quot;devtools&quot;)

## Carregar o pacote devtools
# devtools::install_github(&quot;hadley/tidyverse&quot;)</code></pre>
<p>Com estes comandos, primeiro instalamos o pacote <code>devtools</code> direto do CRAN e depois utilizamos a função <code>install_github()</code> para instalar o pacote, que é baixado do repositório <a href = "https://github.com/hadley/tidyverse", target = "blank_"> https://github.com/hadley/tidyverse</a>.</p>
</div>
</div>
<div id="uso-de-funcoes" class="section level3">
<h3>Uso de funções</h3>
<p>Perceberam que já experimentamos como usar funções no <code>R</code>? E de duas formas diferentes?</p>
<p>A primeira delas foi quando instalamos os pacotes do CRAN, chamando a função diretamente: <code>install.packages()</code>. Como é uma função da base do <code>R</code> ela já está carregada automaticamente no ambiente e trabalho e, por isso, não é preciso carregar um pacote para usá-la.</p>
<p>A segunda delas foi quando instalamos do GitHub. Neste caso, como a função é do pacote <code>devtools</code>, foi preciso indicar o pacote. Por isso escrevemos o nome do pacote à esquerda e, com o uso do operador <code>::</code> assinalamos à direita a função desejada: <code>devtools::install_github(&quot;repositorio-do-github)</code>. Esta forma geralmente é utilizada em dois casos durante um processo de análise: quando queremos explicitar os pacotes que estamos usando, ou quando não usaremos muito as funções daquele pacote e queremos evitar de carregá-lo no ambiente de trabalho.</p>
<p>Mas não é preciso escrever o nome do pacote e usar o operador <code>::</code> toda vez que vai-se utilizar uma função de algum pacote. Isto é tedioso e cansativo. Se trata-se uma função que será bastante usada, você pode carregar o pacote no ambiente de trabalho com a função <code>library()</code>. Neste caso instalaríamos o pacote do GitHub da seguinte forma:</p>
<pre class="r"><code>## Carregar pacote
# library(devtools)

## Usar função
# install_github(&quot;hadley/tidyverse&quot;)</code></pre>
<p>Ao carregar o pacote todas as funções ficam disponíveis no ambiente de trabalho. Então é possível chamá-las diretamente, sem indicar o pacote. Esta é a forma mais usada no dia a dia.</p>
<hr />
</div>
</div>
<div id="o-basico-sobre-dados" class="section level2">
<h2>O básico sobre dados</h2>
<p>Antes de partir para a análise, propriamente, aqui nesta parte veremos rapidamente alguma definições e conceitos básicos para a condução de qualquer tipo de análise de dados, com qualquer tipo de software.</p>
<div id="tipos-de-variaveis" class="section level3">
<h3>Tipos de variáveis</h3>
<p>Entre as definições principais estão os tipos de dados. Conhecer os tipos de dados é importante porque eles servem para situações diferentes e definem formas de manipulação e visualização específicas. Ainda que neste curso não entraremos no tópico da modelagem de dados, os tipos de dados também são determinantes de quais são os modelos adequados.</p>
<ol style="list-style-type: lower-alpha">
<li><p><strong>Variáveis quantitivas</strong>: são aquelas que representam uma determina medida, que mensuram alguma quantidade, a respeito de uma unidade de observação.</p></li>
<li><p><strong>Variáveis qualitativas</strong>: são aquelas que representam uma determinada qualidade de uma unidade de observação.</p></li>
</ol>
<p>Além destes dois tipos de variáveis, lidaremos também com um tipo um pouco diferente, que são as variáveis lógicas.</p>
<ol start="3" style="list-style-type: lower-alpha">
<li><strong>Variáveis lógicas</strong>: são dados representados pelos valores Verdadeiro (<em>TRUE</em>) ou Falso (<em>FALSE</em>).</li>
</ol>
</div>
<div id="classificacao-das-variaveis" class="section level3">
<h3>Classificação das variáveis</h3>
<div class="figure" style="text-align: center"><span id="fig:variaveis"></span>
<img src="img/classificacao_variaveis.png" alt="Classificação das variáveis" width="50%" height="80%" />
<p class="caption">
Figure 4: Classificação das variáveis
</p>
</div>
<div id="variaveis-quantitativas" class="section level4">
<h4>Variáveis quantitativas</h4>
<p>Variáveis quantitativas invarialmente são numéricas e, como dito, mensuram uma quantidade. Elas podem ser divididas em dois tipos:</p>
<ul>
<li><p><strong>Variáveis discretas</strong>: são os números inteiros em um conjunto finito ou infinito de números. Eles, em tese, podem ser ordenados e usualmente representam contagens, como número de filhos ou número de aulas em um ano. No <code>R</code> os números inteiros são representados pela classe <code>int</code> (<em>intergers</em>).</p></li>
<li><p><strong>Variáveis contínuas</strong>: são números reais, por exemplo probabilidades, índices ou razões, e podem ser caracterizados por decimais <span class="math inline">\((3,84)\)</span>. No <code>R</code> as variáveis contínuas são representados pela classe <code>num</code> (<em>numeric</em>).</p></li>
</ul>
</div>
<div id="variaveis-qualitativas" class="section level4">
<h4>Variáveis qualitativas</h4>
<p>Os dados qualitativos são aqueles que não representam valores numéricos. Em geral as variáveis deste tipo são caracterizadas por valores textuais (caracteres ou <em>strings</em>). São também chamados de dados categóricos, pois seus valores em geral representam categorias de uma variável.</p>
<p>As variáveis qualitativas também são divididas em dois tipos:</p>
<ul>
<li><p><strong>Variáveis nominais</strong>: são variáveis cuja lógica interna não implica em ordenamento das categorias, para que a variável faça sentido.</p></li>
<li><p><strong>Variáveis ordinais</strong>: ao contrário, são variáveis que dependem de um determinado ordenamento para que sejam efetivamente interpretadas.</p></li>
</ul>
<p>No <code>R</code> os dados categóricos são representados pela classe <code>chr</code> (<em>character</em>) ou pela classe <code>factor</code>.</p>
</div>
</div>
<div id="estrutura-dos-dados" class="section level3">
<h3>Estrutura dos dados</h3>
<p>Além dos tipos de dados, que dizem respeito às variáveis, há também algumas definições importantes que estão associadas ao conjunto de dados como um todo, seja ele feito de uma ou <span class="math inline">\(n\)</span> variáveis. No <code>R</code> estas estruturas também são chamadas de classes. Há muitas classes de dados diferentes, que podem ser por exemplo matrizes, vetores, listas, data frames, entre outras.</p>
</div>
<div id="observacoes-variaveis-e-data-frames" class="section level3">
<h3>Observações, variáveis e <em>data frames</em></h3>
<p>Neste curso vamos trabalhar basicamente com dados de classe <code>data.frame</code>, sem nos preocupar muito com outros tipos de estrutura. O motivo disto é que os <em>data frames</em> são os que mais se parecem com os dados em planilha com os quais a maior parte das pessoas está acostumada a trabalhar em programas como o Microsoft Excel ou o LibreOffice Calc e são relativamente fáceis de entender, acessar e manipular, apropriada para um curso introdutório.</p>
<p>Este tipo de estrutura de dados, por definição, é feita de um conjunto de observações (linhas) e variáveis (colunas). Cada linha, portanto, corresponde uma unidade de observação e cada coluna apresenta uma determinada característica desta observação, seja ela qualitativa ou quantitativa.</p>
<div class="admonition note">
<p class="admonition-title">
<em>Data frame</em>
</p>
<p>
Data frame é uma lista de variáveis que, por definição, tem o mesmo número de linhas e nomes de linhas únicos. Este tipo de estrutura de dados é dado pela classe <code>data.frame</code>, que é uma das principais estruturas de dados do <code>R</code>, muito útil quando estamos lidando com dados em formato de tabela, incluindo tanto variáveis numéricas como categóricas.
</p>
</div>
<p>Agora que já experimentamos o uso da linha de comando, temos uma noção básica do uso de operadores e de funções, no próximo tópico usaremos o <code>R</code> para identificar estas características em um conjunto de dados e experimentar na prática uma análise dos dados.</p>
</div>
<div id="formas-de-analise" class="section level3">
<h3>Formas de análise</h3>
<p>As ferramentas de descrição dos dados são tabelas, gráficos e medidas de resumo. São elas que nos ajudam a organizar e resumir os dados, de modo a poder interpretá-los.</p>
<p>As formas de análise de distribuições e os tipos de visualizações para os tipos de variáveis podem ser resumidos da seguinte maneira:</p>
<ul>
<li><p><strong>Variáveis qualitativas (nominais ou ordinais)</strong>: são as mais fáceis de analisar. Usualmente controem-se tabelas de frequência para resumir os dados, sendo que as mais comuns são as de frequência absoluta ou relativa. Os gráficos de barra são básicos e apropriados para a visualização de distribuições de frequências de variáveis categóricas. A única diferença no tratamento é que no caso das ordinais é preciso ater-se à ordenação das categorias.</p></li>
<li><p><strong>Variáveis quantitativas discretas</strong>: são tratadas conforme a diversidade de valores presentes na variável. Se são poucos os valores, o tratamento pode ser igual ao das variáveis qualitativas ordinais, isto é, a produção de uma tabela de frequências, com visualização por meio de um gráfico de barras. Se tem muitos valores diferentes, por sua vez, a saíde é agrupar os valores, criando uma variável categórica ordinal, e então analisar a distribuição.</p></li>
<li><p><strong>Variáveis quantitativas contínuas</strong>: no caso das variáveis contínuas, podemos dar o mesmo tratamento dado às variáveis discretas como muitos valores distintos, para analisar frequências, mas podemos também usar formas de visualização como os boxplots, histogramas ou gráficos de densidade.</p></li>
</ul>
<p>Além disso, para analisar as variáveis numéricas utilizaremos medidas-resumo, que servem para sintetizar informações sobre a distribuição das variáveis em apenas uma mensuração. São elas:</p>
<ul>
<li><p><strong>Medidas de tendência central</strong>: média, mediana e moda</p></li>
<li><p><strong>Medidas de dispersão</strong>: amplitude, intervalo interquartil, desvio padrão e coeficiente de variação</p></li>
</ul>
<hr />
</div>
</div>
<div id="analise-descritiva" class="section level2">
<h2>Análise descritiva no R</h2>
<p>A meta do curso é aprendermos a realizar uma análise exploratória de dados com o <code>R</code>. Entraremos neste assuntos mais detidamente depois, mas de forma geral a análise exploratória busca obter <em>insights</em> em relação a algum problema em particular (ou muitas vezes encontrar problemas para investigar).</p>
<p>Um outro tipo de análise de dados é a descritiva, geralmente o primeiro passo no estudo dos dados que foram coletados. Quando vai realizar a análise de um conjunto de dados, é preciso se apropriar deles, mas a simples observação dos dados em planilha não permite extrair conclusões. Ao invés de orientada por problemas, a análise descritiva visa então organizar, resumir e descrever as variáveis analisadas para retratar as características de indivíduos, grupos, fenômenos.</p>
<p>A análise exploratória prescinde do conhecimento e do entendimento a respeito das características que os dados apresentam. Por isto, a análise descritiva pode ser entendida como uma primeira etapa da exploração dos dados.</p>
<p>Podemos descrever os passos de uma análise descritiva no <code>R</code> da seguinte forma:</p>
<ol style="list-style-type: decimal">
<li><p>Importação dos dados</p></li>
<li><p>Caracterização dos dados</p>
<ul>
<li>Qual o tamanho do conjunto de dados? (observações e variáveis)</li>
<li>Estrutura dos dados e tipos de variáveis</li>
<li>Quanto dado está faltando?</li>
</ul></li>
<li><p>Descrição dos dados</p>
<ul>
<li>Análise univariada (amplitudes e frequências)</li>
<li>Análise bi e multivariada (relações entre variáveis)</li>
</ul></li>
</ol>
<p>Nesta aula veremos o exemplo até a análise bivariada.</p>
<div id="importar-dados" class="section level3">
<h3>Importar dados</h3>
<p>A primeira coisa que precisamos é importar os dados para o ambiente de trabalho do <code>R</code>. No caso usaremos o conjunto de dados presente no arquivo <code>aula01.csv</code>, que está na pasta <code>/aula01/dados</code> do diretório do projeto.</p>
<p>Importar um arquivo do tipo <code>.csv</code> é muito simples e pode ser feito com a função <code>read.csv(&quot;caminho-para-arquivo-csv&quot;, outros argumentos opcionais)</code>.</p>
<pre class="r"><code># 1. Importar os dados no R
df &lt;- read.csv(&quot;dados/aula01.csv&quot;, stringsAsFactors = FALSE)</code></pre>
<div class="admonition note">
<p class="admonition-title">
Importar arquivos .csv
</p>
<p>
Os arquivos com extensão <code>.csv</code> são estruturados num formato no qual os valores são separados por vírgulas (<em>comma separated values</em>). A função <code>read.csv()</code> interpreta este formato e o carrega no ambiente como um <code>data.frame</code>.
</p>
</div>
<p>Se está usando o RStudio, você deve ter visto que na parte superior direita da janela do programa, na aba “<em>Environment</em>” (Ambiente), o conjunto de dados que você carregou com o código acima foi importado para um objeto chamado <code>df</code>. Tente clicar no objeto <code>df</code> para ver o que acontece. O RStudio tem um visualizador de dados, que os exibe em forma de planilha.</p>
<p>Este <em>dataset</em> é uma amostra da base de microdados do Censo 2010 para São Paulo (Capital), contendo dados de pessoas com idade entre 18 e 65 anos ocupadas na semana de referência, residentes em 5 áreas de ponderação da cidade selecionadas aleatoramente (são 310 ao todo). As unidades de observação, portanto, são as pessoas respondentes do questionário do Censo 2010.</p>
<p>As variáveis são as seguintes:</p>
<ul>
<li><p><code>Raca</code>: raça da pessoa</p></li>
<li><p><code>Sexo</code>: sexo da pessoa</p></li>
<li><p><code>Estado Civil</code>: indica o estado civil</p></li>
<li><p><code>NumPessoasFam</code>: indica o número de pessoas na família</p></li>
<li><p><code>IdadeAnos</code>: a idade da pessoa, em anos</p></li>
<li><p><code>RendTrabPrinc</code>: renda mensal da pessoa no trabalho principal</p></li>
<li><p><code>RendTrabDemais</code>: renda nos demais trabalhos, além do principal</p></li>
<li><p><code>RendOutrasFontes</code>: renda oriunda de outras fontes que não o trabalho</p></li>
</ul>
</div>
<div id="checar-e-caracterizar-os-dados" class="section level3">
<h3>Checar e caracterizar os dados</h3>
<div id="checar-os-dados" class="section level4">
<h4>Checar os dados</h4>
<p>Antes de começar a descrever o conteúdo das variáveis, é aconselhável checar se os dados foram corretamente carregados e identificar as características das variáveis com as quais você está lidando.</p>
<p>Uma forma de checar e confirmar se está tudo certo é dar uma olhada no começo e no final do <em>dataset</em>, o que pode nos indicar se houve algum erro.</p>
<p>Extrair apenas as primeiras linhas de um objeto de dados no <code>R</code> pode ser feito facilmente com a função <code>head()</code>. Já as últimas linhas podem ser acessadas por meio da função <code>tail()</code>. Vejamos os exemplos abaixo.</p>
<pre class="r"><code># 3. Visualizar o começo dos dados
head(df)</code></pre>
<pre><code>##     Raca      Sexo EstadoCivil NumPessoasFam IdadeAnos RendTrabPrinc
## 1 Branca Masculino   Casado(a)             3        31             0
## 2 Branca  Feminino   Casado(a)             3        64             0
## 3 Branca  Feminino   Casado(a)             4        48             0
## 4 Branca Masculino Solteiro(a)             4        22             0
## 5 Branca  Feminino Solteiro(a)             4        26             0
## 6 Branca Masculino Solteiro(a)             4        34             0
##   RendTrabDemais RendOutrasFontes
## 1              0                0
## 2              0                0
## 3              0                0
## 4              0                0
## 5              0                0
## 6              0                0</code></pre>
<pre class="r"><code># 4. Visualizar o fim dos dados
tail(df)</code></pre>
<pre><code>##        Raca      Sexo   EstadoCivil NumPessoasFam IdadeAnos RendTrabPrinc
## 4368 Branca  Feminino Divorciado(a)             2        40          6000
## 4369  Preta Masculino Divorciado(a)             3        42          5000
## 4370 Branca  Feminino   Solteiro(a)             3        51          3500
## 4371 Branca  Feminino   Solteiro(a)             1        44          8600
## 4372 Branca  Feminino   Solteiro(a)             1        43          7500
## 4373 Branca  Feminino   Solteiro(a)             2        27         10000
##      RendTrabDemais RendOutrasFontes
## 4368              0                0
## 4369           1000                0
## 4370           3000               50
## 4371           2000              750
## 4372              0              300
## 4373              0             3000</code></pre>
<p>O resultado das funções <code>head()</code> e <code>tail()</code> são as 6 primeiras e as 6 últimas linhas do conjunto de dados, respectivamente. Pode ser que em alguns momentos você esteja interessado em extrair mais ou menos do que seis observações do começo ou do fim. Isto pode ser feito adicionando um valor para o argumento <code>n</code> nas duas funções. Veja os exemplos abaixo.</p>
<pre class="r"><code>head(df, n = 2)</code></pre>
<pre><code>##     Raca      Sexo EstadoCivil NumPessoasFam IdadeAnos RendTrabPrinc
## 1 Branca Masculino   Casado(a)             3        31             0
## 2 Branca  Feminino   Casado(a)             3        64             0
##   RendTrabDemais RendOutrasFontes
## 1              0                0
## 2              0                0</code></pre>
<pre class="r"><code>tail(df, n = 2)</code></pre>
<pre><code>##        Raca     Sexo EstadoCivil NumPessoasFam IdadeAnos RendTrabPrinc
## 4372 Branca Feminino Solteiro(a)             1        43          7500
## 4373 Branca Feminino Solteiro(a)             2        27         10000
##      RendTrabDemais RendOutrasFontes
## 4372              0              300
## 4373              0             3000</code></pre>
<p>O número de observações extraídas desta vez foi 2, conforme indicamos no argumento <code>n</code>. Qualquer valor que você indicar neste argumento será usado pela função. Vale dizer ainda que explicitar o argumento muitas vezes é opcional, porque o programa os interpretará de acordo com a sua posição na função. Tente, por exemplo, rodar o código <code>head(df, 3)</code> no console:</p>
<pre class="r"><code># desmarque a linha abaixo para rodar o comando
# head(df, 3)</code></pre>
</div>
<div id="caracterizacao-dos-dados" class="section level4">
<h4>Caracterização dos dados</h4>
<p>Estando tudo certo, é recomendável verificar informações sobre a estrutura do objeto e os tipos de variáveis. Um bom recurso para isto é a função <code>str()</code>. Ela gera uma saída (<em>output</em>) na qual a primeira linha apresenta a classe da estrutura dos dados e cada linha seguinte apresenta um resumo com o nome, o tipo e os primeiros valores de cada variável.</p>
<pre class="r"><code># 2. Verificar a estrutura dos dados
str(df)</code></pre>
<pre><code>## &#39;data.frame&#39;:    4373 obs. of  8 variables:
##  $ Raca            : chr  &quot;Branca&quot; &quot;Branca&quot; &quot;Branca&quot; &quot;Branca&quot; ...
##  $ Sexo            : chr  &quot;Masculino&quot; &quot;Feminino&quot; &quot;Feminino&quot; &quot;Masculino&quot; ...
##  $ EstadoCivil     : chr  &quot;Casado(a)&quot; &quot;Casado(a)&quot; &quot;Casado(a)&quot; &quot;Solteiro(a)&quot; ...
##  $ NumPessoasFam   : int  3 3 4 4 4 4 3 3 3 2 ...
##  $ IdadeAnos       : int  31 64 48 22 26 34 20 25 30 42 ...
##  $ RendTrabPrinc   : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ RendTrabDemais  : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ RendOutrasFontes: int  0 0 0 0 0 0 0 0 0 0 ...</code></pre>
<p>Pela saída gerada acima, é possível notar as seguintes características:</p>
<ul>
<li><p>Com relação à estrutura, os dados foram importados como um <code>data.frame</code>, como queríamos;</p></li>
<li><p>A respeito da dimensão do conjunto de dados, ele tem 4373 linhas (observações) e 8 colunas (variáveis);</p></li>
<li><p>Entre as variáveis, 5 são numéricas, todas elas discretas (classe <code>int</code>);</p></li>
<li><p>Há 3 variáveis categóricas (classe <code>chr</code>), todas elas nominais.</p></li>
</ul>
</div>
<div id="identificar-dados-faltantes" class="section level4">
<h4>Identificar dados faltantes</h4>
<p>Se uma variável apresenta grande quantidade de valores ausentes (<code>NA</code>), ela pode não ser útil para análise. É apropriado então buscar identificar o peso dos valores faltantes em cada variável.</p>
<p>A função <code>is.na()</code> serve para identificar os popularmente chamados <code>NAs</code>. Ela analisa os dados e retorna em valores lógicos a resposta se o dado está ou não faltando. Pense nesta função como uma forma de perguntar: “<em><code>R</code>, este dado é faltante?</em>”. Se sim, portanto, ela retornará <code>TRUE</code>; se não, ela retornará <code>FALSE</code>.</p>
<p>Vamos fazer um teste no nosso objeto <code>df</code>, apenas para as primeiras linhas:</p>
<pre class="r"><code>is.na(head(df))</code></pre>
<pre><code>##    Raca  Sexo EstadoCivil NumPessoasFam IdadeAnos RendTrabPrinc
## 1 FALSE FALSE       FALSE         FALSE     FALSE         FALSE
## 2 FALSE FALSE       FALSE         FALSE     FALSE         FALSE
## 3 FALSE FALSE       FALSE         FALSE     FALSE         FALSE
## 4 FALSE FALSE       FALSE         FALSE     FALSE         FALSE
## 5 FALSE FALSE       FALSE         FALSE     FALSE         FALSE
## 6 FALSE FALSE       FALSE         FALSE     FALSE         FALSE
##   RendTrabDemais RendOutrasFontes
## 1          FALSE            FALSE
## 2          FALSE            FALSE
## 3          FALSE            FALSE
## 4          FALSE            FALSE
## 5          FALSE            FALSE
## 6          FALSE            FALSE</code></pre>
<p>Se fizéssemos este teste para toda a base de dados, utilizando apenas <code>is.na(df)</code>, teríamos dito para a função identificar os <code>NAs</code> em todas as mais de 4000 linhas, gerando um resultado extenso e desagradável. Tente rodar <code>is.na(df)</code> no seu console e veja o resultado. Por este motivo pedimos para o <code>R</code> investigar apenas as primeiras linhas, selecionadas com a função <code>head()</code>.</p>
<div class="admonition message">
<p class="admonition-title">
No <code>R</code> tudo é um objeto
</p>
<p>
Percebeu que, para fazer isto, nós aninhamos uma função dentro da outra? Isto é possível porque no <code>R</code> toda saída é também um objeto de dados, que pode ser manipulado por outras funções.
</p>
</div>
<p>Vamos fazer isto em mais etapas para entender.</p>
<pre class="r"><code># guardas as primeiras seis linhas
linhas &lt;- head(df)
# visualizar
linhas</code></pre>
<pre><code>##     Raca      Sexo EstadoCivil NumPessoasFam IdadeAnos RendTrabPrinc
## 1 Branca Masculino   Casado(a)             3        31             0
## 2 Branca  Feminino   Casado(a)             3        64             0
## 3 Branca  Feminino   Casado(a)             4        48             0
## 4 Branca Masculino Solteiro(a)             4        22             0
## 5 Branca  Feminino Solteiro(a)             4        26             0
## 6 Branca Masculino Solteiro(a)             4        34             0
##   RendTrabDemais RendOutrasFontes
## 1              0                0
## 2              0                0
## 3              0                0
## 4              0                0
## 5              0                0
## 6              0                0</code></pre>
<pre class="r"><code># investigar presença de NAs
is.na(linhas)</code></pre>
<pre><code>##    Raca  Sexo EstadoCivil NumPessoasFam IdadeAnos RendTrabPrinc
## 1 FALSE FALSE       FALSE         FALSE     FALSE         FALSE
## 2 FALSE FALSE       FALSE         FALSE     FALSE         FALSE
## 3 FALSE FALSE       FALSE         FALSE     FALSE         FALSE
## 4 FALSE FALSE       FALSE         FALSE     FALSE         FALSE
## 5 FALSE FALSE       FALSE         FALSE     FALSE         FALSE
## 6 FALSE FALSE       FALSE         FALSE     FALSE         FALSE
##   RendTrabDemais RendOutrasFontes
## 1          FALSE            FALSE
## 2          FALSE            FALSE
## 3          FALSE            FALSE
## 4          FALSE            FALSE
## 5          FALSE            FALSE
## 6          FALSE            FALSE</code></pre>
<p>Viu o que fizemos? Neste caso, ao invés de aninhar as funções, primeiro guardamos a saída de <code>head(df)</code> no objeto <code>linhas</code> e depois pedimos para o programa analisar a presença de <code>NAs</code> com <code>is.na(linhas)</code>. Como <code>head(df)</code> <span class="math inline">\(=\)</span> <code>linhas</code>, então <code>is.na(head(df))</code> <span class="math inline">\(=\)</span> <code>is.na(linhas)</code>. Por isso no final das contas o resultado é o mesmo, mas da primeira forma que fizemos somos mais suscintos e economizamos linhas de código e tempo.</p>
<p>Ainda assim, não temos o que queremos, que é a quantidade de <code>NAs</code> em cada variável. Queremos um resultado resumido, com a soma de todos os valores <code>TRUE</code> de cada uma das colunas. Isto é possível de ser feito com outra função, a <code>colSums()</code>, que faz justamente isto: soma os valores de uma coluna.</p>
<p>Precisamos apenas usar as funções <code>is.na()</code> e <code>colSums()</code> conjuntamente:</p>
<pre class="r"><code>colSums(is.na(df))</code></pre>
<pre><code>##             Raca             Sexo      EstadoCivil    NumPessoasFam 
##                0                0                0                4 
##        IdadeAnos    RendTrabPrinc   RendTrabDemais RendOutrasFontes 
##                0                0                0                0</code></pre>
<p>Agora sim, podemos ver que apenas a variável <code>NumPessoasFam</code> tem valores faltantes, sendo 4 no total. Isto não compreende nem 1% das mais de 4000 observações, de modo que não deve ser motivo de preocupação.</p>
</div>
</div>
<div id="analise-de-distribuicoes" class="section level3">
<h3>Análise de distribuições</h3>
<p>Para organizar e já apresentar métodos de sumarização e visualização apropriados, vamos dividir a análise pelos tipos de variáveis que temos, sendo uma de cada tipo.</p>
<p>Começaremos a utilizar os pacotes e a linguagem do <code>tidyverse</code>, da qual falamos anteriormente. Então, para disponibilizar suas funções, carregaremos os pacotes no ambiente de trabalho:</p>
<pre class="r"><code>library(dplyr) # para manipular os dados
library(ggplot2) # para visualizar os dados</code></pre>
<p>Em muitos momentos você precisará checar os nomes das colunas do <code>dataset</code>. Neste caso estamos trabalhando com 8 variáveis, mas às vezes muitas mais estão envolvidas. A função <code>name()</code> retorna os nomes quando precisar relembrá-los:</p>
<pre class="r"><code>names(df)</code></pre>
<pre><code>## [1] &quot;Raca&quot;             &quot;Sexo&quot;             &quot;EstadoCivil&quot;     
## [4] &quot;NumPessoasFam&quot;    &quot;IdadeAnos&quot;        &quot;RendTrabPrinc&quot;   
## [7] &quot;RendTrabDemais&quot;   &quot;RendOutrasFontes&quot;</code></pre>
<div id="variaveis-categoricas-nominais" class="section level4">
<h4>Variáveis categóricas nominais</h4>
<p><strong>Distribuição de <code>Raca</code></strong></p>
<p>A variável categórica nominal que analisaremos é a raca (<code>Raca</code>). Queremos a distribuição de frequências. Observe o código a seguir e seu resultado:</p>
<pre class="r"><code>df %&gt;% count(Raca)</code></pre>
<pre><code>## # A tibble: 5 x 2
##   Raca        n
##   &lt;chr&gt;   &lt;int&gt;
## 1 Amarela    45
## 2 Branca   2832
## 3 Indígen     2
## 4 Parda    1195
## 5 Preta     299</code></pre>
<p>O resultado é uma tabela de <strong>frequência absoluta</strong> das categorias da variável <code>Raca</code>, mostrando que os brancos têm a maior participação de indivíduos na amostra, seguidos dos pardos. As raças preta, amarela e indígena têm bem menor representação.</p>
<p>Ainda assim, muitas vezes é mais interessante analisar a frequência relativa, que indica as proporções de participação de cada categoria na amostra, ao invés da contagem. A seguir calcularemos a frequência relativa, mas antes vamos entender o que fizemos para gerar as frequências.</p>
<p>Na primeira parte do código acima indicamos a nossa base de dados <code>df</code> e utilizamos o operador <code>%&gt;%</code>, chamado de <em>pipe</em>, para conectar a função <code>count()</code>, apontando dentro da função qual a variável cujas categorias queríamos contar. A função <code>count()</code> é uma das muitas do pacote <code>dplyr</code> e é um jeito fácil de gerar tabelas de frequência.</p>
<p>Já o <em>pipe</em> <code>%&gt;%</code> é uma estrutura básica da análise de dados com o <code>tidiverse</code>. Ele separa o acesso ao objeto de dados das funções que estamos utilizando, de maneira que toda operação passada à direita de <code>%&gt;%</code> age sobre tudo o que está à sua esquerda.</p>
<div class="admonition note">
<p class="admonition-title">
<em>Uso dos pipes</em>
</p>
<p>
Os pipes <code>%&gt;%</code> são a grande sacada da linguagem <code>tidyverse</code>. Com eles é possível concatenar linhas de código de forma mais estruturada e sequencial, facilitando a realização de múltiplas operações no mesmo comando.
</p>
</div>
<p>Agora sim vamos incluir o cálculo da <strong>frequência relativa</strong>, o que nos ajudará a entender melhor o uso dos pipes:</p>
<pre class="r"><code>df %&gt;%
  # contar as categorias
  count(Raca) %&gt;%
  # calcular a frequência relativa
  mutate(prop = prop.table(n))</code></pre>
<pre><code>## # A tibble: 5 x 3
##   Raca        n     prop
##   &lt;chr&gt;   &lt;int&gt;    &lt;dbl&gt;
## 1 Amarela    45 0.0103  
## 2 Branca   2832 0.648   
## 3 Indígen     2 0.000457
## 4 Parda    1195 0.273   
## 5 Preta     299 0.0684</code></pre>
<p>Percebam que adicionamos mais uma etapa de manipulação no código e como resultado temos tanto a contagem das frequências absolutas, como o cálculo da relativa.</p>
<p>Lembra que falamos anteriormente que, pelo fato de tudo no <code>R</code> ser um objeto de dados é possível concatenar funções? O mesmo vale aqui.</p>
<p>Nós primeiro indicamos que o objeto <code>df</code> seria acessado para calcular a contagem da variável raça com <code>count(Raca)</code>, que gerou um novo objeto (volte e veja o resultado de quando calculamos apenas a contagem). A etapa seguinte, depois do segundo <em>pipe</em> <code>%&gt;%</code> trabalha com este objeto e não mais com a base <code>df</code>.</p>
<p>Por isto é possível encadear mais uma etapa, no caso com a função <code>mutate()</code> do pacote <code>dplyr</code>, que permite realizar transformações e computar novas variáveis. Dentro de dela usamos a função <code>prop.table()</code> para criar a variável <code>prop</code> com as proporções.</p>
<p>Voltando-nos ao resultado, agora podemos afirmar facilmente que mais de 82% das observações da amostra são relativas a pessoas de raça branca ou parta, e que as raças amarela, indígena e preta formam os 18% restantes. Informação mais significativa e interpretável do que a dada pela frequência absoluta.</p>
<p>Para terminar com esta variável vamos visualizar a distribuição com o pacote <code>ggplot2</code>. Desta vez vamos repetir o cálculo anterior, mas diferentemente usaremos o sinal de atribuição para guardar o resultado em um objeto e, depois, usar este objeto para criar o gráfico.</p>
<pre class="r"><code># calcular as frequências
freq &lt;- df %&gt;%
  count(Raca) %&gt;%
  mutate(prop = prop.table(n))
# visualizar
freq</code></pre>
<pre><code>## # A tibble: 5 x 3
##   Raca        n     prop
##   &lt;chr&gt;   &lt;int&gt;    &lt;dbl&gt;
## 1 Amarela    45 0.0103  
## 2 Branca   2832 0.648   
## 3 Indígen     2 0.000457
## 4 Parda    1195 0.273   
## 5 Preta     299 0.0684</code></pre>
<p>Agora vamos utilizar o objeto <code>freq</code> para plotar a distribuição:</p>
<pre class="r"><code>ggplot(freq, aes(x = Raca, y = prop)) + # cria o canvas e define estética
  geom_bar(stat = &quot;identity&quot;) # coloca o gráfico de barras</code></pre>
<p><img src="/aula01/index_files/figure-html/unnamed-chunk-28-1.png" width="80%" height="80%" /></p>
<p>Deste jeito fica muito mais fácil de interpretar, não fica? Vamos agora etender o código que gerou este gráfico de barras.</p>
<p>Para criar o <em>plot</em> utilizamos três funções:</p>
<ul>
<li><p><code>ggplot()</code>: é a função principal, que cria um <em>canvas</em>, um painel em branco, no qual os elementos gráficos serão colocados;</p></li>
<li><p><code>aes()</code>: é uma função que mapeia os dados aos elementos que deverão representá-los. No caso utilizamos o argumento <code>x</code>, indicando que a variável categórica <code>Raca</code> seria plotada no eixo X, e o argumento <code>y</code>, indicando que a variável numérica <code>prop</code> seria plotada no eixo Y.</p></li>
<li><p><code>geom_bar</code>: determina a geometria do gráfico de barras para plotar os dados e coloca os elementos gráficos no <em>canvas</em> criado pela função <code>ggplot()</code>. O argumento <code>stat = &quot;identity&quot;</code> especifica que o tamanho das barras deve ser igual ao valor da variável indicada para o eixo Y.</p></li>
</ul>
<p>Cada camada do gráfico é adicionada com o operador <code>+</code>. O <code>+</code> funciona no contexto do <code>ggplot2</code> da mesma forma que o <code>%&gt;%</code> no contexto do <code>dplyr</code>. Assim, com <code>ggplot()</code> criamos a primeira camada e com <code>geom_bar()</code> criamos a segunda.</p>
<p>Para que o gráfico fique um pouco mais informativo, podemos adicionar uma terceira etapa no código para incluir uma camada com os rótulos das proporções de cata categoria.</p>
<pre class="r"><code>ggplot(freq, aes(x = Raca, y = prop)) + # cria o canvas
  geom_bar(stat = &quot;identity&quot;) + # coloca o gráfico de barras
  geom_label(aes(label = round(prop, 4))) # coloca o rótulo</code></pre>
<p><img src="/aula01/index_files/figure-html/unnamed-chunk-29-1.png" width="80%" height="80%" /></p>
<p>Agora sim. Muito melhor, não é? A função <code>geom_label()</code> faz o papel de adicionar os rótulos das categorias. Ela pega a informação do argumento <code>label</code>, que foi acrescentado dentro da função <code>aes(... , label = ...)</code>.</p>
<p>Perceba que no argumento <code>aes(label = ...)</code>, ao invés de apenas passar a variável <code>prop</code>, para que os valores de proporções fossem extraídos desta coluna, utilizamos a função <code>round(prop, 4)</code>. A tabela anterior mostra que os valores percentuais têm muitas casas decimais e isto deixaria o gráfico estranho. Por isso usamos a função <code>round()</code>, para arredondar os números, e com a indicação de que isto deveria ser feito até a quarta casa decimal.</p>
<p>Quando usamos <code>round(prop, 4)</code> foi como se disséssemos: “<code>R</code>, arredonde a variável <code>prop</code> até a quarta casa decimal”.</p>
</div>
<div id="variaveis-quantitativas-discretas" class="section level4">
<h4>Variáveis quantitativas discretas</h4>
<p><strong>Distribuição de <code>NumPessoasFam</code></strong></p>
<p>Quando os dados são numéricos, geralmente começamos por calcular algumas medidas de resumo, que ajudam a compreender a distribuição das variáveis. Uma forma muito simples de acessar medidas resumo é com função <code>summary()</code>, que faz parte da base do <code>R</code>.</p>
<pre class="r"><code>summary(df$NumPessoasFam)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##   1.000   2.000   3.000   3.493   4.000  11.000       4</code></pre>
<p>Com menos de 30 caracteres de código são gerados os valores mínimo e máximo, a média e a mediana, o primeiro e terceiro quartis, e a quantidade de valores ausentes.</p>
<p>Este modo é realmente muito simples. Ainda assim, em geral precisamos computar estas medidas individualmente, ou precisamos de medidas de variabilidade que não são geradas como <code>summary()</code>. Para gerar individualmente as medidas-resumo que mais serão usadas no curso, são usadas as seguintes funções:</p>
<ul>
<li><p><code>mean()</code>: calcula a média</p></li>
<li><p><code>median()</code>: calcula a mediana</p></li>
<li><p><code>min()</code>: identifica o menor valor</p></li>
<li><p><code>max()</code>: identifica o maior valor</p></li>
<li><p><code>sd()</code>: calcula o desvio padrão</p></li>
<li><p><code>IQR()</code>: calcula o interval0 interquartil</p></li>
</ul>
<p>As utilizaremos mais tarde no curso, em conjunto com os verbos dos pacotes <code>dplyr</code> e <code>tidyr</code>, para comparar resumos estatísticos em análises bivariadas.</p>
<p>Vamos agora visualizar a distribuição de <code>NumPessoasFam</code>. Trata-se de uma variável numérica discreta, com amplitude igual a 11. Não sendo muitos os valores distintos, podemos então tratá-los como se fossem variáveis categóricas ordinais, calculando as frequências com <code>count()</code> e plotando os dados em um gráfico de barras com <code>geom_bar()</code>.</p>
<pre class="r"><code># calcular as frequẽncias
freq &lt;- df %&gt;%
  # contar os valores
  count(NumPessoasFam) %&gt;%
  # calcular a frequência relativa
  mutate(prop = prop.table(n))

# plotar o gráfico
ggplot(freq, aes(x = NumPessoasFam, y = prop)) +
  geom_bar(stat = &quot;identity&quot;)</code></pre>
<p><img src="/aula01/index_files/figure-html/unnamed-chunk-31-1.png" width="80%" height="80%" /></p>
<p>Aqui não colocamos os rótulos. No caso de distribuições quantitativas, as quantidades ou proporções individuais de cada categoria são menos importantes do que caso de variáveis qualitativas.</p>
<p>Aqui, interessa menos saber que 28% da amostra tem 3 pessoas na família e mais, por exemplo, que a distribuição é assimétrica à direita e que o centro da distribuição é composto por família com 2 a 4 membros.</p>
</div>
<div id="variaveis-quantitativas-continuas" class="section level4">
<h4>Variáveis quantitativas contínuas</h4>
<p><strong>Distribuição de <code>RendTrabPrinc</code></strong></p>
<p>Como fizemos com a variável anterior, vamos começar gerando o sumário com <code>summary()</code>.</p>
<pre class="r"><code>summary(df$RendTrabPrinc)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##       0     700    1000    2065    2000   50000</code></pre>
<p>Tipicamente, variáveis de renda contam com <strong>outliers</strong> (valores discrepantes), que estão associados a graus de desigualdade.</p>
<p>O sumário indica isto. Entre os habitantes da cidade de São Paulo que residem nas áreas de ponderação incluídas na amostra, a renda no trabalho principal varia de 0 a 50.000. Porém, 50% recebe até R$ 1.000 na principal fonte de renda e e 75% da amostra recebe até R$ 2.000.</p>
<p>Vamos visualizar esta distribuição. Já que estamos lindando com uma variável contínua, podemos recorrer a um histograma, que embora parecido com o gráfico de barras, é feito para distribuições contínuas. No <code>ggplot2</code> um histograma é gerado com <code>geom_histogram()</code>.</p>
<pre class="r"><code>ggplot(df, aes(x = RendTrabPrinc)) +
  geom_histogram()</code></pre>
<p><img src="/aula01/index_files/figure-html/unnamed-chunk-33-1.png" width="80%" height="80%" /></p>
<p>Ao invés de <code>geom_bar()</code> utilizamos <code>geom_histogram()</code>.</p>
<p>A distribuição é tão fortemente assimétrica à direita que até atrapalha a visualização da distribuição, pois os dados estão muito concentrados na escala até um pouco acima de R$ 10.000.</p>
<p>Nestes casos podemos considerar que valores acima de R$ 10.000, por exemplo, não são relevantes na visualização, e limitar o Eixo X, de maneira que apenas os casos com renda até este valor sejam mostrados.</p>
<p>Resolver este problema depende de adicionarmos mais uma etapa no código do gráfico para manipular a escala do eixo X com a função <code>scale_x_continuous()</code>, assim como trabalhamos com a inclusão dos rótulos na análise da variável <code>Raca</code>.</p>
<pre class="r"><code>ggplot(df, aes(x = RendTrabPrinc)) +
  geom_histogram(bins = 25)  +
  scale_x_continuous(limits = c(0, 10000))</code></pre>
<p><img src="/aula01/index_files/figure-html/unnamed-chunk-34-1.png" width="80%" height="80%" /></p>
<p>Além disso, adicionamos dois argumentos na função, um em <code>geom_histogram()</code> e outro em <code>scale_x_continuous</code>:</p>
<ul>
<li><p><code>bins</code>: controle o número de colunas que serão exibidas no histograma. No caso pedimos para dividir em 25 colunas (<code>bins = 25</code>);</p></li>
<li><p><code>limits</code>: controla os limites do eixo X. Como trata-se de uma combinação de valores (o mais baixo e mais alto), usamos a função <code>c()</code> para indicar os limites de 0 a 10.000 (<code>limites = c(0, 10000)</code>).</p></li>
</ul>
<p>Atrás falamos dos <em>outliers</em>, que são valores que destoam muito do centro da distribuição. Um gráfico adequado para analisar no caso de variáveis com esta característica é o <em>boxplot</em>, que no <code>ggplot2</code> é construído com a função <code>geom_boxplot()</code>.</p>
<p>Observe o código a seguir:</p>
<pre class="r"><code>ggplot(df, aes(y = RendTrabPrinc)) +
  geom_boxplot() +
  scale_y_continuous(limits = c(0, 10000))</code></pre>
<p><img src="/aula01/index_files/figure-html/unnamed-chunk-35-1.png" width="80%" height="80%" /></p>
<p>Fizemos apenas algumas pequenas alterações no código que gerou o histograma. Ao invés do eixo X, no <em>boxplot</em> a escala dos dados é disposta no eixo Y. Então mapeamos os dados usando o argumento <code>y</code> (<code>aes(y = RendTrabPrinc)</code>) e também mudamos <code>scale_x_continuous()</code> por <code>scale_y_continuous()</code>.</p>
</div>
</div>
<div id="como-aprender-o-r" class="section level3">
<h3>Como aprender o R</h3>
<p>Ainda que você faça outros cursos presenciais como este, ou cursos on line como os oferecidos em plataformas como Coursera, Edx ou DataCamp, você aprenderá muito com os recursos de ajuda porque será a eles que você recorrerá no seu dia a dia.</p>
<p>Os recursos para aprender o R são pricipalmente os seguintes:</p>
<ol style="list-style-type: decimal">
<li><strong>Documentação das funções</strong></li>
</ol>
<p>No <code>R</code> podemos consultar qualquer função utilizando <code>?função</code> ou então com função help <code>help(função)</code>. Tente rodar no sua máquina o pedaço de código que está abaixo.</p>
<pre class="r"><code>help(read.csv)</code></pre>
<p>O mesmo resultado será obtido da seguinte maneira:</p>
<pre class="r"><code>?read.csv</code></pre>
<p>A maior parte do seu aprendizado sobre <code>R</code> ocorrerá enquanto consulta as documentações dos pacotes e funções e também as discussões e dicas da comunidade.</p>
<ol start="2" style="list-style-type: decimal">
<li><strong>Google</strong></li>
</ol>
<p>Se você olhou a documentação e não conseguiu entender o que fazer, ou se você nem sabe pode onde começar, procure no Google. Há milhares de tutoriais, documentações criadas por usuários, listas de discussão, livros, uma infinidade de materiais que podem te ajudar a fazer o que você quer.</p>
<ol start="3" style="list-style-type: decimal">
<li><strong>Stack Overflow</strong></li>
</ol>
<p>É uma comunidade incrível onde desenvolvedores e programadores de todas as linguagens podem pedir ajuda e contribuir com as dúvidas alheias. A comunidade do <code>R</code> é bastante ativa no <a href = "https://stackoverflow.com/questions/tagged/r",
target = "blank_"><strong>Stack Overflow</strong></a>.</p>
<hr />
</div>
</div>
<div id="sintese-da-aula" class="section level2">
<h2>Síntese da aula</h2>
<p>Aqui resumimos rapidamente o conteúdo desta aula em tópicos:</p>
<div id="aspectos-introdutorios" class="section level3">
<h3>Aspectos introdutórios</h3>
<ul>
<li>Os programas <code>R</code> e RStudio</li>
<li>Uso de funções e operadores no <code>R</code></li>
<li>Istalação de pacotes</li>
<li>Checagem dos dados</li>
<li>Estrutura de dados no <code>R</code> e tipos de variáveis</li>
<li>Criação de tabelas de frequência com <code>count()</code></li>
<li>Criação de gráficos (barras, histograma, <em>boxplot</em>)</li>
<li>Encadeamento de funções com o <em>pipe</em> <code>%&gt;%</code></li>
<li>Como obter ajuda</li>
</ul>
</div>
<div id="operadores" class="section level3">
<h3>Operadores</h3>
<ul>
<li><p><code>::</code> – é usado após o nome de um pacote para chamar uma função (<code>pacote::função()</code>)</p></li>
<li><p><code>$</code> – o cifrão é usado para acessar variáveis em um <em>data frame</em> (<code>objeto$variavel</code>)</p></li>
<li><p><code>&lt;-</code> – o sinal de atribuição é usado para guardar dados em um objeto</p></li>
<li><p><code>=</code> – também atribui valores, mas em geral é usado para argumentos de funções</p></li>
<li><p><code>%&gt;%</code> – o <em>pipe</em> faz parte do <code>tidyverse</code> e permite encadear múltiplas operações</p></li>
</ul>
</div>
<div id="funcoes" class="section level3">
<h3>Funções</h3>
<p><strong>Da base do <code>R</code></strong>:</p>
<ul>
<li><p><code>c()</code>: combina valores</p></li>
<li><p><code>install.packages()</code>: instala pacotes do CRAN</p></li>
<li><p><code>devtools::install_github()</code>: instala pacotres do GitHub</p></li>
<li><p><code>read.csv()</code>: importa dados <code>.csv</code></p></li>
<li><p><code>head()</code>: extrai as primeiras linhas do <em>dataset</em></p></li>
<li><p><code>tail()</code>: extrai as últimas linhas do <em>dataset</em></p></li>
<li><p><code>str()</code>: gera informações sobre o conjunto de dados e as variáveis</p></li>
<li><p><code>summary()</code>: sumarisa as variáveis</p></li>
<li><p><code>is.na()</code>: busca os valores faltantes</p></li>
<li><p><code>colSums()</code>: soma os valores das colunas</p></li>
<li><p><code>prop.table()</code>: calcula proporções</p></li>
<li><p><code>round()</code>: arredonda os valores de uma variável</p></li>
<li><p><code>help()</code>: consultar documentação de uma função ou pacote</p></li>
</ul>
<p><strong>Do <code>dplyr</code></strong>:</p>
<ul>
<li><p><code>dplyr::mutate()</code>: permite transformar variáveis ou criar novas</p></li>
<li><p><code>dplyr::count()</code>: gera as frequências de variáveis categóricas</p></li>
</ul>
<p><strong>Do <code>ggplot2</code></strong>:</p>
<ul>
<li><p><code>ggplot()</code>: cria um canvas para incluir elementos gráficos</p></li>
<li><p><code>aes()</code>: mapeia os dados aos elementos gráficos</p></li>
<li><p><code>geom_bar()</code>: plota um gráfico de barras</p></li>
<li><p><code>geom_histogram()</code>: plota um histograma</p></li>
<li><p><code>geom_boxplot()</code>: plota um boxplot</p></li>
<li><p><code>geom_label()</code> plota os rótulos</p></li>
<li><p><code>scale_x_continuous()</code>: manipula o Eixo X do gráfico</p></li>
<li><p><code>scale_y_continuous()</code>: manipula o Eixo Y do gráfico</p></li>
</ul>
<hr />
</div>
</div>
<div id="exercicios" class="section level2">
<h2>Exercícios</h2>
<p>Agora vamos praticar o que vimos nesta aula. Os três exercício a seguir devem ser realizados individualmente, de forma ordenada, já que cada tarefa prepara para a realização da seguinte.</p>
<div id="exercicio-1-analise-a-distribuicao-de-frequencias-da-variavel-sexo" class="section level3">
<h3>Exercício 1: Analise a distribuição de frequências da variável <code>Sexo</code></h3>
<ol style="list-style-type: lower-alpha">
<li>Altere os traços <code>___</code> no código abaixo com o valor <code>Sexo</code>, para produzir uma tabela de frequências.</li>
</ol>
<pre class="r"><code># # calcular as frequências
# freq &lt;- df %&gt;%
#   count(___) %&gt;%
#   mutate(prop = prop.table(n))</code></pre>
<ol start="2" style="list-style-type: lower-alpha">
<li>Agora use o objeto criado no passo anterior para criar o gráfico de barras da distribuição. Troque os primeiros traços por <code>freq</code> e o segundo por <code>Sexo</code>.</li>
</ol>
<pre class="r"><code># # visualizar os dados
# ggplot(___, aes(x = ___, y = prop, label = round(prop, 4))) +
#   geom_bar(stat = &quot;identity&quot;) +
#   geom_label()</code></pre>
<ol start="3" style="list-style-type: lower-alpha">
<li>Agora reutilize o código das duas etapas acima para plotar a distribuição de frequências da variável <code>EstadoCivil</code>.</li>
</ol>
<blockquote>
<p><em>Dica</em>: cole os códigos anteriores no próximo <em>chunk</em> e depois substitua <code>Sexo</code> por <code>EstadoCivil</code>.</p>
</blockquote>
<pre class="r"><code># cole ou digite abaixo o seu código</code></pre>
</div>
<div id="exercicio-2-analise-a-distribuicao-da-variavel-numpessoasfam" class="section level3">
<h3>Exercício 2: Analise a distribuição da variável <code>NumPessoasFam</code></h3>
<ol style="list-style-type: lower-alpha">
<li>Analise o código abaixo e o histograma criado, depois siga as orientações:</li>
</ol>
<pre class="r"><code>ggplot(df, aes(x = IdadeAnos)) +
  geom_histogram()</code></pre>
<p><img src="/aula01/index_files/figure-html/unnamed-chunk-41-1.png" width="80%" height="80%" /></p>
<p>Veja na mensagem gerada que, por padrão, o histograma é plotado com 30 colunas. Agora manipule a quantidade de colunas do histograma para 25, incluindo este parâmetro no argumento <code>bin = ___</code>.</p>
<pre class="r"><code># Cole aqui o código acima e faça as modificações necessárias</code></pre>
<ol start="2" style="list-style-type: lower-alpha">
<li>Agora reutilize o código acima para plotar um boxplot com a distribuição da variável <code>IdadeAnos</code>.</li>
</ol>
<pre class="r"><code># Cole aqui o código acima e faça as modificações necessárias</code></pre>
</div>
<div id="exercicio-3-analise-a-distribuicao-de-idade-por-estado-civil" class="section level3">
<h3>Exercício 3: Analise a distribuição de idade por estado civil</h3>
<p>Este exercício é uma forma de conhecer mais sobre o potencial do <code>ggplot2</code>.</p>
<p>Até agora só fizemos análises univariadas, sem explorar a relação entre as variáveis da nossa base de dados. Converter análises de uma variável em análises entre uma um mais variáveis é bastante fácil.</p>
<p>Observe o código e o boxplot gerado abaixo e depois siga as instruções.</p>
<pre class="r"><code>ggplot(df, aes(x = Sexo, y = IdadeAnos)) +
  geom_boxplot()</code></pre>
<p><img src="/aula01/index_files/figure-html/unnamed-chunk-44-1.png" width="80%" height="80%" /></p>
<p>Agora reutilize o código acima para gerar um boxplot da distribuição de idade em relação ao estado civil.</p>
<pre class="r"><code># Cole aqui o código acima e faça as modificações necessárias</code></pre>
</div>
</div>
